before_script: cd java
language: java
jdk: oraclejdk11
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.headless=true -Dprism.order=sw"
    - JAVADOC_FILES=($(git diff --name-only $TRAVIS_COMMIT_RANGE | grep -i "java/doc"))
before_deploy:
  - mvn package
deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    file: "build/tetris.jar"
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    github_token: $GITHUB_JAVADOC_DEPLOY_TOKEN
    keep_history: true
    local_dir: "java/doc"
    on:
      branch: master
      condition: ! -z $JAVADOC_FILES
addons:
  sonarcloud:
    organization: "klenium-github"
    token:
      secure: $SONAR_TOKEN
before_install:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar