before_script: cd java
language: java
jdk: oraclejdk11
cache:
  directories:
    - $HOME/.m2
# before_install:
#   - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
env:
  - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.headless=true -Dprism.order=sw"
before_deploy:
  - mvn package
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: "build/tetris.jar"
  skip_cleanup: true
  on:
    tags: true
addons:
  sonarcloud:
    organization: "klenium-github"
    token:
      secure: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar