before_script: cd java
language: java
jdk:
    - oraclejdk11
cache:
    directories:
        - $HOME/.m2
before_deploy:
    - mvn package
deploy:
    provider: releases
    api_key: $GH_TOKEN
    file: "build/tetris.jar"
    skip_cleanup: true
    on:
        tags: true